services:
  vuln-db:
    image: mysql:8.0
    container_name: vuln-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: insecure_app
      MYSQL_USER: insecure_user
      MYSQL_PASSWORD: insecure_pass
    ports:
      - "3307:3306" # pour ne pas entrer en conflit avec un Ã©ventuel MySQL local
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
    command: >
      mysqld --default-authentication-plugin=mysql_native_password
             --character-set-server=utf8mb4
             --collation-server=utf8mb4_unicode_ci
    healthcheck:
      test: [ "CMD-SHELL", "mysql -h localhost -u insecure_user -pinsecure_pass -e 'SELECT 1' || exit 1" ]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 5s

  vuln-web:
    build: ./web
    container_name: vuln-web
    environment:
      DB_HOST: vuln-db
      DB_USER: insecure_user
      DB_PASSWORD: insecure_pass
      DB_NAME: insecure_app
    depends_on:
      vuln-db:
        condition: service_healthy
    ports:
      - "8080:3000" # http://localhost:8080
